DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3R1c2VyMkBibGFoLmNvbSIsImV4cCI6MTcyNjAxNzMzOCwidXNlcklkIjoyfQ.gNngAswwFCzfOfYrl5au8WGry_bBQjI0AKLdxfb0KVs